{% set name = "sshpubkeys" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3020ed4f8c846849299370fbe98ff4157b0ccc1accec105e07cfa9ae4bb55064

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - cryptography >=2.1.4
    - ecdsa >=0.13
    - python

test:
  imports:
    - sshpubkeys

about:
  home: https://github.com/ojarva/python-sshpubkeys
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: SSH public key parser
  dev_url: https://github.com/ojarva/python-sshpubkeys

extra:
  recipe-maintainers:
    - mariusvniekerk
