{% set name = "sshpubkeys" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sshpubkeys-{{ version }}.tar.gz
  sha256: 3020ed4f8c846849299370fbe98ff4157b0ccc1accec105e07cfa9ae4bb55064

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cryptography >=2.1.4
    - ecdsa >=0.13
    - python >={{ python_min }}

test:
  imports:
    - sshpubkeys
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ojarva/python-sshpubkeys
  summary: SSH public key parser
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mariusvniekerk
